# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c50a10a8792af3590b87dc1540c7666b2888bb010a49fbfc904ada9bc93943c4a580f7c8ab8af13268da5546667caba51b63ead8569bd10f0dbfde01ca5c0346

test:
  secret_key_base: 27ae15c24d449717c5a165508290dd352e7e599a306d8a05c4c33e63c252ccfe4009d2d0354fe971fa3c6f143929b545652f844509ce44dc1392ea3540ed7220

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
